version: "3"
services:
  springapp:
    build: .
    container_name: springapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/YOURDB
    ports:
      - 8000:8080
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=YOURUSR
      - POSTGRES_PASSWORD=YOURPASS
      - POSTGRES_DB=YOURDB
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: