version: "4"
services:
  airlineweb:
    build: .
    container_name: airlineweb
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/airline
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=airline
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5000:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: