<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <h1>Purchase process ${id}</h1>

    <div>
        <form method="post">
            Card number
            <input type="number" name="cardNumber" placeholder="16 digit card number" /><br>
            Security code (CVV/CVC)
            <input type="number" name="securityCode" placeholder="Example: 792" /><br>
            Expiry Date
            <input type="text" name="expiryDate" placeholder="Example: 07/25" /><br>
        </form>
    </div>
</head>
<body>

</body>
</html>